# Generated by Django 2.2a1 on 2019-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=500)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('GERMANY', 'GERMANY'), ('SPAIN', 'SPAIN'), ('RUSSIA', 'RUSSIA'), ('FRANCE', 'FRANCE'), ('ENGLAND', 'ENGLAND')], max_length=500)),
                ('captain', models.CharField(max_length=500)),
                ('manager', models.CharField(max_length=500)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
