# Generated by Django 2.2a1 on 2019-08-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='potfolio_sie',
            new_name='portfolio_site',
        ),
    ]
